---

apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  INFLUXDB_ADMIN_USER: {{ .Values.influxdb.adminUser | toJson | b64enc }}
  INFLUXDB_ADMIN_USER_PASSWORD: {{ .Values.influxdb.adminPassword | toJson | b64enc }}
  INFLUXDB_DB: {{ .Values.influxdb.db | toJson | b64enc }}
  INFLUXDB_HOST: {{ .Values.influxdb.host | toJson | b64enc }}
  INFLUXDB_HTTP_AUTH_ENABLED: {{ .Values.influxdb.httpAuthEnabled | toJson | b64enc }}
  INFLUXDB_READ_USER: {{ .Values.influxdb.readUser | toJson | b64enc }}
  INFLUXDB_USER: {{ .Values.influxdb.user | toJson | b64enc }}
  INFLUXDB_USER_PASSWORD: {{ .Values.influxdb.userPassword | toJson | b64enc }}
