---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  type: {{ .Values.influxdb.service.type | default "ClusterIP"}}
